export const DESSERT_LIST_REQUEST = "DESSERT_LIST_REQUEST";
export const DESSERT_LIST_SUCCESS = "DESSERT_LIST_SUCCESS";
export const DESSERT_LIST_FAIL = "DESSERT_LIST_FAIL";

export const DESSERT_DETAILS_REQUEST = "DESSERT_DETAILS_REQUEST";
export const DESSERT_DETAILS_SUCCESS = "DESSERT_DETAILS_SUCCESS";
export const DESSERT_DETAILS_FAIL = "DESSERT_DETAILS_FAIL";

export const DESSERT_DELETE_REQUEST = "DESSERT_DELETE_REQUEST";
export const DESSERT_DELETE_SUCCESS = "DESSERT_DELETE_SUCCESS";
export const DESSERT_DELETE_FAIL = "DESSERT_DELETE_FAIL";

export const DESSERT_CREATE_REQUEST = "DESSERT_CREATE_REQUEST";
export const DESSERT_CREATE_SUCCESS = "DESSERT_CREATE_SUCCESS";
export const DESSERT_CREATE_FAIL = "DESSERT_CREATE_FAIL";
export const DESSERT_CREATE_RESET = "DESSERT_CREATE_RESET";

export const DESSERT_UPDATE_REQUEST = "DESSERT_UPDATE_REQUEST";
export const DESSERT_UPDATE_SUCCESS = "DESSERT_UPDATE_SUCCESS";
export const DESSERT_UPDATE_FAIL = "DESSERT_UPDATE_FAIL";
export const DESSERT_UPDATE_RESET = "DESSERT_UPDATE_RESET";
